### ISSUE TITLE
Waveform Simulator

### ISSUE THREAD

**Issue by pdeperio** [akutsuR/MDT#2]
Need to port the waveform simulator from https://github.com/WatChMaL/WatChMaL/pull/24 to here.

Blair and Sydney's summary slides: [TruthInfo_WaveFormSim_Leggett_Jamieson.pdf](https://github.com/akutsuR/MDT/files/10964573/TruthInfo_WaveFormSim_Leggett_Jamieson.pdf)

**Comment by pdeperio** [comment]
Details from Thomas:

Marcin has provided the expected response of mPMT electronics for a 1PE pulse.  The [attached text file](https://github.com/akutsuR/MDT/files/11328021/LC-gauss.txt) has the pulse shape (in Volts vs seconds) for a 1PE pulse.  The picture shows the shape pictorially.

![mpmt_pulse_shape_1pe](https://user-images.githubusercontent.com/8642192/234441727-57f0e6fd-d2e0-459d-8a1e-eaa16b8f4702.png)

As you can see the pulse shape is not going to be easy to represent with any analytic form; I guess you will probably need to just use this empirical pulse shape.

Note that we may be slightly tweaking this pulse shape as we do the final set of tests of the mainboard.  So it would be nice if you kept your software implementation generic enough that we could update the pulse shape in a couple months.

I guess you will also want to be simulating the digitizer and data suppression.

The digitizer is a 2V, 12-bit digitizer, running at 125MHz (8ns per sample).

For data suppression, we will be doing one of the following:

1) Doing pulse finding online to find pulses 
and saving ~20-40 ADC samples around the pulse.

2) Doing pulse finding online to find pulses, doing some pulse processing and saving only a time, a charge and a fit quality for each pulse (maybe some other quantities too).

For the immediate future we will probably be using 1) more, as we work to understand the electronics.  So it is probably more important to have a simulation of 1) first.  But I guess we will need the flexibility to simulate both.

**Comment by akutsuR** [comment]
I think we need a pulse height distribution at 1PE level, otherwise integral of the waveform (= charge) will be always a constant.if same integration window is  used. Have you already discussed this point with anybody ?

**Comment by pdeperio** [comment]
Copied to https://github.com/WCTE/MDT/issues/2
